spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/firstProject
    username: postgres
    password: 2001
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
